services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "my_volume_mongodb:/data/db"
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - carbon-calc

networks:
  carbon-calc:
    driver: bridge

volumes:
  my_volume_mongodb: